export const ABOUT_DATA = {
    __typename: "LandingEntity",
    attributes: {
        __typename: "Landing",
        name: "About Us Landing",
        label: "about-us-landing",
        banners: {
            __typename: "BannerRelationResponseCollection",
            data: [
                {
                    __typename: "BannerEntity",
                    attributes: {
                        __typename: "Banner",
                        name: "About us brief banner",
                        label: "about-us-brief-banner",
                        title: "At Novatech, our people are the core of our business",
                        subtitle: null,
                        description:
                            "We focus on having one of the best work environments in the region. Our main objective is having an enthusiastic and motivated team. We support the growth of each of our members by crafting a career plan that aligns with their personal and professional goals​.",
                        isFloating: false,
                        top: null,
                        left: null,
                        right: null,
                        bottom: null,
                        haveAction: false,
                        actionLabel: null,
                        actionRoute: null,
                        hero: {
                            __typename: "UploadFileEntityResponse",
                            data: {
                                __typename: "UploadFileEntity",
                                attributes: {
                                    __typename: "UploadFile",
                                    name: "image_coworkers.png",
                                    formats: {
                                        thumbnail: {
                                            name: "thumbnail_image_coworkers.png",
                                            hash: "thumbnail_image_coworkers_a2c413b45e",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 234,
                                            height: 156,
                                            size: 68.92,
                                            path: null,
                                            url: "/uploads/thumbnail_image_coworkers_a2c413b45e.png",
                                        },
                                        large: {
                                            name: "large_image_coworkers.png",
                                            hash: "large_image_coworkers_a2c413b45e",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 1000,
                                            height: 667,
                                            size: 991.14,
                                            path: null,
                                            url: "/uploads/large_image_coworkers_a2c413b45e.png",
                                        },
                                        medium: {
                                            name: "medium_image_coworkers.png",
                                            hash: "medium_image_coworkers_a2c413b45e",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 750,
                                            height: 500,
                                            size: 583.16,
                                            path: null,
                                            url: "/uploads/medium_image_coworkers_a2c413b45e.png",
                                        },
                                        small: {
                                            name: "small_image_coworkers.png",
                                            hash: "small_image_coworkers_a2c413b45e",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 500,
                                            height: 333,
                                            size: 275.12,
                                            path: null,
                                            url: "/uploads/small_image_coworkers_a2c413b45e.png",
                                        },
                                    },
                                },
                            },
                        },
                        background: {
                            __typename: "UploadFileEntityResponse",
                            data: {
                                __typename: "UploadFileEntity",
                                attributes: {
                                    __typename: "UploadFile",
                                    name: "bg_core.png",
                                    formats: {
                                        thumbnail: {
                                            name: "thumbnail_bg_core.png",
                                            hash: "thumbnail_bg_core_6a6c877553",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 245,
                                            height: 105,
                                            size: 28,
                                            path: null,
                                            url: "/uploads/thumbnail_bg_core_6a6c877553.png",
                                        },
                                        large: {
                                            name: "large_bg_core.png",
                                            hash: "large_bg_core_6a6c877553",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 1000,
                                            height: 431,
                                            size: 370.55,
                                            path: null,
                                            url: "/uploads/large_bg_core_6a6c877553.png",
                                        },
                                        medium: {
                                            name: "medium_bg_core.png",
                                            hash: "medium_bg_core_6a6c877553",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 750,
                                            height: 323,
                                            size: 215.62,
                                            path: null,
                                            url: "/uploads/medium_bg_core_6a6c877553.png",
                                        },
                                        small: {
                                            name: "small_bg_core.png",
                                            hash: "small_bg_core_6a6c877553",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 500,
                                            height: 215,
                                            size: 100.82,
                                            path: null,
                                            url: "/uploads/small_bg_core_6a6c877553.png",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                {
                    __typename: "BannerEntity",
                    attributes: {
                        __typename: "Banner",
                        name: "About us banner",
                        label: "about-us-banner",
                        title: "We are a Nearshore software development company specialized in web and mobile solutions​",
                        subtitle: null,
                        description:
                            "At Novatech we become your strategic technological partner. We offer customized solutions and services across multiple industries.",
                        isFloating: false,
                        top: null,
                        left: null,
                        right: null,
                        bottom: null,
                        haveAction: false,
                        actionLabel: null,
                        actionRoute: null,
                        hero: {
                            __typename: "UploadFileEntityResponse",
                            data: null,
                        },
                        background: {
                            __typename: "UploadFileEntityResponse",
                            data: {
                                __typename: "UploadFileEntity",
                                attributes: {
                                    __typename: "UploadFile",
                                    name: "about us.png",
                                    formats: {
                                        thumbnail: {
                                            name: "thumbnail_about us.png",
                                            hash: "thumbnail_about_us_ee811e1e19",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 222,
                                            height: 156,
                                            size: 64.8,
                                            path: null,
                                            url: "/uploads/thumbnail_about_us_ee811e1e19.png",
                                        },
                                        large: {
                                            name: "large_about us.png",
                                            hash: "large_about_us_ee811e1e19",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 1000,
                                            height: 702,
                                            size: 1083.64,
                                            path: null,
                                            url: "/uploads/large_about_us_ee811e1e19.png",
                                        },
                                        medium: {
                                            name: "medium_about us.png",
                                            hash: "medium_about_us_ee811e1e19",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 750,
                                            height: 527,
                                            size: 616.35,
                                            path: null,
                                            url: "/uploads/medium_about_us_ee811e1e19.png",
                                        },
                                        small: {
                                            name: "small_about us.png",
                                            hash: "small_about_us_ee811e1e19",
                                            ext: ".png",
                                            mime: "image/png",
                                            width: 500,
                                            height: 351,
                                            size: 283.55,
                                            path: null,
                                            url: "/uploads/small_about_us_ee811e1e19.png",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            ],
        },
        video_boxes: {
            __typename: "VideoBoxRelationResponseCollection",
            data: [
                {
                    __typename: "VideoBoxEntity",
                    attributes: {
                        __typename: "VideoBox",
                        title: "Best place to work!",
                        subtitle: null,
                        label: "best-place-to-work",
                        video: "hDS7tSFRCck",
                    },
                },
            ],
        },
        mission_and_vision_banner: {
            __typename: "MissionAndVisionBannerEntityResponse",
            data: {
                __typename: "MissionAndVisionBannerEntity",
                attributes: {
                    __typename: "MissionAndVisionBanner",
                    title: "Mission & vision",
                    subtitle: null,
                    mission:
                        "Help companies acquire and sustain a competitive advantage through technology.",
                    vision: "Become a leader in the digital transformation sector in Latin America.",
                    missionIcon: {
                        __typename: "UploadFileEntityResponse",
                        data: {
                            __typename: "UploadFileEntity",
                            attributes: {
                                __typename: "UploadFile",
                                name: "mission.png",
                                formats: null,
                            },
                        },
                    },
                    visionIcon: {
                        __typename: "UploadFileEntityResponse",
                        data: {
                            __typename: "UploadFileEntity",
                            attributes: {
                                __typename: "UploadFile",
                                name: "vision.png",
                                formats: null,
                            },
                        },
                    },
                    background: {
                        __typename: "UploadFileEntityResponse",
                        data: {
                            __typename: "UploadFileEntity",
                            attributes: {
                                __typename: "UploadFile",
                                name: "visonmision.png",
                                formats: {
                                    thumbnail: {
                                        name: "thumbnail_visonmision.png",
                                        hash: "thumbnail_visonmision_8aaa62c0e7",
                                        ext: ".png",
                                        mime: "image/png",
                                        width: 205,
                                        height: 156,
                                        size: 32.48,
                                        path: null,
                                        url: "/uploads/thumbnail_visonmision_8aaa62c0e7.png",
                                    },
                                    large: {
                                        name: "large_visonmision.png",
                                        hash: "large_visonmision_8aaa62c0e7",
                                        ext: ".png",
                                        mime: "image/png",
                                        width: 1000,
                                        height: 760,
                                        size: 710.69,
                                        path: null,
                                        url: "/uploads/large_visonmision_8aaa62c0e7.png",
                                    },
                                    medium: {
                                        name: "medium_visonmision.png",
                                        hash: "medium_visonmision_8aaa62c0e7",
                                        ext: ".png",
                                        mime: "image/png",
                                        width: 750,
                                        height: 570,
                                        size: 398.47,
                                        path: null,
                                        url: "/uploads/medium_visonmision_8aaa62c0e7.png",
                                    },
                                    small: {
                                        name: "small_visonmision.png",
                                        hash: "small_visonmision_8aaa62c0e7",
                                        ext: ".png",
                                        mime: "image/png",
                                        width: 500,
                                        height: 380,
                                        size: 175.92,
                                        path: null,
                                        url: "/uploads/small_visonmision_8aaa62c0e7.png",
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
};
